Intro:
  pages:
    intro/preface: "Preface"
    intro/secondary: "Protocol Documentation"
Protocol:
  pages:
    protocol/contract-offer: "Contract offer"
    protocol/contract-formation: "Contract Formation"
    protocol/contract-amendment: "Contract Amendment"
    protocol/static-contract-formation: "Static Contract Formation"
    protocol/asset-definition: "Asset Definition"
    protocol/asset-creation: "Asset Creation"
    protocol/asset-modification: "Asset Modification"
    protocol/send: "Send"
    protocol/exchange: "Exchange"
    protocol/swap: "Swap"
    protocol/settlement: "Settlement"
    protocol/initiative: "Initiative"
    protocol/referendum: "Referendum"
    protocol/vote: "Vote"
    protocol/ballot-cast: "Ballot Cast"
    protocol/ballot-counted: "Ballot Counted"
    protocol/result: "Result"
    protocol/order: "Order"
    protocol/freeze: "Freeze"
    protocol/thaw: "Thaw"
    protocol/confiscation: "Confiscation"
    protocol/reconciliation: "Reconciliation"
    protocol/message: "Message"
    protocol/rejection: "Rejection"
